name: Update events

on:
  watch:
    types: started
  schedule:
    - cron:  '0 */18 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    concurrency:
      group: update-events
      cancel-in-progress: true

    steps:
      - name: Check out repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            $GOPATH/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Fetch events
        run: go run main.go

      - name: Commit and push if changed
        run: |
          git config --global user.email "bot@github.com"
          git config --global user.name "Bot"
          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m ":memo: 更新自述"
            git push
          fi
